### PR TITLE
Upgraded to dotnet 7

### PR DESCRIPTION
**Pull request by MartinSchmidt**
Updated to dotnet 7

This PR should be merged after #37

### CODE REVIEW

**Review by guidmaster — APPROVED** [review]
May I suggest to introduce a Directory.Build.props file. In that file we could have something like 

```xml
<PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <WarningsAsErrors>nullable</WarningsAsErrors>
</PropertyGroup>
```
By introcucing this file we would have a single place that we to change in the future.

**Comment by MartinSchmidt** [comment]
Good point, I looked at it a bit this morning, but I am running into an issue, when we have two of the libraries, (electricity.client and PedersenCommitment) which we have multiple targets on (net6 and net7) it then overrides these as well and only produces a net7.

@guidmaster do you have any experience which this?

**Comment by guidmaster** [comment]
> 
@MartinSchmidt in cases like that I would just create a new Directory.Build.prop in those projects.

**Comment by MartinSchmidt** [comment]
@guidmaster I did as you requested my liege 👑

**Review by guidmaster — APPROVED** [review]

**Pull request merged**
